name: Deploy
on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    # 🤷 https://github.community/t/workflow-run-completed-event-triggered-by-failed-workflow/128001
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Build catalog export
      run: bundle exec rake export

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
        PRESERVE: true # Preserves and restores the workspace prior to deployment.
